# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Build and E2E Test

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            SHIP: ship-linux
            # https://github.com/microsoft/playwright/issues/11932
            E2E: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2e:ci
          - os: macos-latest
            SHIP: ship-mac
            E2E: yarn test:e2e:ci
          - os: windows-latest
            SHIP: ship-win
            E2E: yarn test:e2e:ci

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18

      - run: yarn install --immutable

      - name: Increase watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        if: matrix.os == 'ubuntu-latest'

      - name: Build app
        run: yarn ${{ matrix.SHIP }}

      - name: Run end-to-end tests
        run: ${{ matrix.E2E }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: artifacts
          path: src/e2e-tests/artifacts
          retention-days: 30
