# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Check code quality

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18

      - run: yarn install --immutable

      - run: yarn format-check

      - run: yarn lint-check

      - run: yarn typecheck

      - run: yarn test:unit
