# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use yarn cache (linux, mac)
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        if: matrix.os != 'windows-latest'

      - name: Use yarn cache (win)
        uses: actions/cache@v3
        with:
          path: '**\node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**\yarn.lock') }}
        if: matrix.os == 'windows-latest'

      - run: yarn install --frozen-lockfile --prefer-offline --network-timeout 560000

      - name: Increase watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        if: matrix.os == 'ubuntu-latest'

      - run: yarn lint-check
      - run: yarn compile-all
      - run: yarn test:unit
      - run: yarn test:integration-ci
